#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
"""
"""
import sys
import os
import argparse
from moviepy.editor import *

parent_dir = os.path.dirname(os.path.abspath(__file__))

def summarize(filename):
    filename = os.path.join(parent_dir, filename)
    clip = VideoFileClip(filename).subclip(0, 60)

    txt_clip = TextClip("Video summarization generated by vSummarize -- Lucas Ou-Yang",
        fontsize=20, color='white')
    txt_clip = txt_clip.set_pos('bottom').set_duration(20)

    # Overlay the text clip above the first clip
    final_clip = CompositeVideoClip([clip, txt_clip])

    final_clip.to_videofile("solution.mp4", fps=25, codec='mpeg4')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='download and summarize youtube videos')
    parser.add_argument('-f', '--filename', type=str, default='', help='Enter a filename')
    parser.add_argument('-u', '--url', type=str, default='', help='Enter a youtube url')
    args = parser.parse_args()

    filename, url = args.filename, args.url
    print 'filename:', filename, 'url:', url
    summarize(filename)
