#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
import sys
import os

from moviepy.editor import *

def summarize(filepath, new_filename, hotclips):
    """
    Inputs a filepath for a video and generates a new shorter video
    in that same filepath.
    """
    clips = []
    for start, end in hotclips:
        try:
            chunked_clip = VideoFileClip(filepath).subclip(start, end)
            """
            # This was for testing, leave for now.
            one = VideoFileClip('YkADj0TPrJA.mp4').subclip(10, 15)
            two = VideoFileClip('YkADj0TPrJA.mp4').subclip(17, 20)
            three = VideoFileClip('YkADj0TPrJA.mp4').subclip(24, 27)
            four = VideoFileClip('YkADj0TPrJA.mp4').subclip(28, 30)
            five = VideoFileClip('YkADj0TPrJA.mp4').subclip(31, 35)
            f=concatenate([one, two, three, four, five])
            f.to_videofile('finished.mp4', fps=25, audio_codec='mp3', codec='mpeg4')
            """
        except Exception, e:
            print 'ERROR when chunking video', str(e)
            continue
        clips.append(chunked_clip)

    final_clip = concatenate(clips)
    # txt_clip = TextClip("Generated by vSummarize", fontsize=20, color='white')
    # txt_clip = txt_clip.set_pos('bottom').set_duration(20)
    # final_clip = CompositeVideoClip([clip, txt_clip])
    try:
        final_clip.to_videofile(new_filename, fps=25, audio_codec='mp3', codec='mpeg4')
    except Exception, e:
        print 'ERROR when generating output video', str(e)

    os.remove(filepath) # remove the full youtube .mp4, only keep the summary

if __name__ == '__main__':
    summarize('YkADj0TPrJA.mp4', 'finished.mp4',
        [(10, 15), (17, 20), (24, 27), (28, 30), (31, 35)])
