#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
import sys
import os
from moviepy.editor import *

def summarize(filepath, new_filename, hotclips):
    """
    Inputs a filepath for a video and generates a new shorter video
    in that same filepath.
    """
    clips = []
    for start, end in hotclips:
        try:
            chunked_clip = VideoFileClip(filepath).subclip(start, end)
        except Exception, e:
            print 'ERROR when chunking video', str(e)
        clips.append(chunked_clip)

    final_clip = concatenate(clips)
    # txt_clip = TextClip("Generated by vSummarize", fontsize=20, color='white')
    # txt_clip = txt_clip.set_pos('bottom').set_duration(20)
    # final_clip = CompositeVideoClip([clip, txt_clip])
    try:
        final_clip.to_videofile(new_filename, fps=25, audio_codec='mp3', codec='mpeg4')
    except Exception, e:
        print 'ERROR when generating output video', str(e)

if __name__ == '__main__':
    summarize('zRCsZ5a3aCM.mp4', [(0,5), (10,15)])
